app = 'mail-dispatcher-demo'
primary_region = 'nrt'

[build]

[deploy]
  strategy = "immediate"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  DATABASE_URL = "file:/data/prod.db"
  EMAIL_MODE = "console"
  DEMO_MODE = "true"
  NEXT_PUBLIC_DEMO_MODE = "true"

[[mounts]]
  source = "sqlite_data"
  destination = "/data"
  initial_size = "1gb"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
